---
title: "Coral_Bleaching_Class"
author: "Raymond Infante"
date: "2023-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
#Packages
```


```{r, message=FALSE, echo=FALSE, warning=FALSE}
```


```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(performance)
library(scales)
```


```{r, message=FALSE, echo=FALSE, warning=FALSE}
#calling the data

CoralTemp = slice(read_csv("NOAA_SST.csv"),-1)

CoralTemp$datetime = as_datetime(CoralTemp$time)
CoralTemp$CRW_SST = as.numeric(CoralTemp$CRW_SST)

CoralTemp

str(CoralTemp)

CoralTemp %>% 
  ggplot(aes(datetime, CRW_SST))+
  geom_point()+
  geom_line()


#Have SST been increasing in La Parguera


SST_model = lm(CRW_SST~datetime, data = CoralTemp)
summary(SST_model) #There is a small detectable (p<0.05) increase in SST in La Parguera from 1985 to 2023
# check the performance of the model
check_model(SST_model)

#We can create a prediction of the model we plot
?predict

CoralTemp_predict = cbind(CoralTemp, predict(SST_model, interval = "confidence", level = 0.95))

view(CoralTemp_predict)

CoralTemp_predict %>% 
  ggplot()+
  geom_line(aes(datetime, CRW_SST), alpha = 0.7, size = 0.8)+
  geom_line(aes(datetime, fit), color = "purple")+
  geom_ribbon(aes(x = datetime, ymin = lwr, ymax = upr), fill = "purple", alpha = 0.2, size = 1)+
  labs(x = "Year", y = "Sea Surface Temperature (°C)")+
  scale_x_datetime(labels = date_format("%Y"),
                   breaks = date_breaks("5 years"),
                   limits = as_datetime(c("1983-01-01 UTC", "2025-01-01 UTC")),
                   expand = c(0,0))+
  scale_y_continuous(limits = c(25,31), breaks = seq(25,31,1))+
  theme_classic()+ 
  theme(text = element_text(size = 14))

max(CoralTemp$time)

#Add a few sentence about CoralTemp and the motivation for quantifying ocean warming and coral bleaching in La Parguera (<5 sentences)
#Describe this figure nad the statistics relating to SST icnreasing in la Parguera since 1985, we will discuss degree heating weeks in our next class. (<5 sentences) 
```



```{r, echo=FALSE}

view(CoralTemp)

coral_temp_climatology = CoralTemp %>% 
  mutate(month = as.numeric(format(datetime, "%m"))) %>% 
  group_by(month) %>% 
  summarise(Mean = mean(CRW_SST), SD = sd(CRW_SST))


coral_temp_climatology %>% 
  ggplot(aes(month,Mean))+
  geom_line(size = 1.3, alpha = 0.8)+
  geom_ribbon(aes(x  = month, y = Mean, ymin = Mean-SD, ymax = Mean+SD),fill = "#a36af7",alpha = 0.3) +
  theme_classic()+
  labs(y = "Sea Surface Temperature (°C)", x = "Month") + theme(axis.title = element_text(size = 15),
    axis.text = element_text(size = 13, colour = "black"),
    axis.text.x = element_text(colour = "black"))+
  scale_x_continuous(limits = c(1,12), breaks = seq(1,12,1))+
  scale_y_continuous(limits = c(25,30),breaks = seq(25,30,1))

#Plotting the degree heating weeks
CoralTemp %>% 
  ggplot()+
  geom_line(aes(x = datetime, y = CRW_DHW))
#Find the times that Degree heating week DHW exceeded 4, which is an indicator of ecologically significant coral bleaching predicted
CoralTemp %>% 
  filter(CRW_DHW>=4)
#This means we expected coral bleaching in what years?
#2005,2010  

CoralTemp %>% 
  ggplot()+
  geom_line(aes(x = datetime, y = CRW_DHW))+
  geom_hline(aes(yintercept = 4), color = "orange")+
  geom_hline(aes(yintercept = 8), color = "red")+
  annotate("text", x = as.POSIXct("2005-10-15 12:00:00"), y = 5.9, label = "2005")+
  annotate("text", x = as.POSIXct("2010-09-17 12:00:00"), y = 5.4, label = "2010")+
  annotate("text",  x = as.POSIXct("1994-08-02 12:00:00"), y = 4.5, label = "Significant Bleaching", color = "orange")+
  annotate("text",  x = as.POSIXct("1994-08-02 12:00:00"), y = 8.2, label = "Severe Bleaching", color = "red")+
  theme_classic()

#Combined lab report discussing SST icnrease and coral bleaching historically and into the future

#Figure 1: Plot of all SST temperature data
#Figure 2: Climatology of monthly mean SST data
#Figure 3: Plot of years we predict coral bleaching
#Figure 4: Future projections of SST/bleaching (in class next week)

  
#Final report = a few sentence of why we are doing this, and then publication figure and text explaining what they mean (show nothing else)
```

Coral temp and motivation of quantifying ocean warming on coral bleaching in La Parguera.

Describe the figure above relating SST increase in La Parguera since 1985. 